# Generated by Django 4.0.4 on 2022-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_category_recipe_delete_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
