# Generated by Django 4.0.4 on 2022-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_recipe_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created']},
        ),
    ]
