# Generated by Django 4.0.4 on 2022-05-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0006_alter_recipe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesapp.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
