# Generated by Django 4.0.4 on 2022-05-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0008_recipe_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rate',
        ),
    ]
