# Generated by Django 4.0.4 on 2022-05-23 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0010_recipe_dislikes_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='recipesapp.userprofile'),
            preserve_default=False,
        ),
    ]
