# Generated by Django 4.0.4 on 2022-05-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0011_recipe_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesapp.userprofile'),
        ),
    ]
