# Generated by Django 4.0.4 on 2022-05-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0012_alter_recipe_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_profile',
        ),
    ]
