# Generated by Django 4.0.4 on 2022-05-24 18:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0013_remove_recipe_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[640, 480], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
